[Network]
Type="channel"
CAFile="./configs/sdk/ca.crt"
Cert="./configs/sdk/sdk.crt"
Key="./configs/sdk/sdk.key"

[[Network.Connection]]
NodeURL="bcos.gm:20201"
GroupID=1

[Account]
KeyFile="./configs/sdk/user.pem"

[Chain]
ChainID=1
SMCrypto=false

[Log]
Path="./"
Level="debug"