[Network]
Type="channel"
CAFile="./configs/sdk/gm/gmca.crt"
Cert="./configs/sdk/gm/gmsdk.crt"
Key="./configs/sdk/gm/gmsdk.key"
EnCert="./configs/sdk/gm/gmensdk.crt"
EnKey="./configs/sdk/gm/gmensdk.key"

[[Network.Connection]]
NodeURL="bcos.gm:20200"
GroupID=1

[Account]
KeyFile="./configs/sdk/gm/user.pem"

[Chain]
ChainID=1
SMCrypto=true

[Log]
Path="./"
Level="debug"